apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: mysql
 namespace: wordpress
spec:
 replicas: 1
 selector:
  matchLabels:
    app: mysql
 template:
  metadata:
   labels:
    app: mysql
  spec:
   containers:
    - image: mysql:5.6
      imagePullPolicy: IfNotPresent
      name: wordpress-mysql
      volumeMounts:
       - name: mysql-data
         mountPath: /var/lib/mysql
      ports:
       - containerPort: 27017
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wordpress
        - name: MYSQL_PASSWORD
          value: password
   volumes:
     - name: mysql-data
       hostPath:
         path: /mnt/data/mysql
